
var courses =  [
  {
    "Introduction to Information Studies": {
      "courseID":"SI 110",
      "Pre-reqs": {},
      "Outcomes": {
        "Explain Important Concepts Related To Study Of Information": "L",
        "Reflect Critically On Own Use Of Info System": "L",
        "Relating Info Frame to Multiple Domains": "L",
        "Write Short  Essays ": "C",
        "Creating compelling deliverables (Creating Hi-Fi prototype in UX)  ": "L",
        "Articulate arguments relating to information policy": "L"
      }
    },
    "Programs, Information and People": {
      "courseID":"SI 106",
      "Pre-reqs": {},
      "Outcomes": {
        "Data Types: creating, parsing": "A",
        "Text: NLP (libraries e.g. NLTK)": "A",
        "Text: standard formats (CSV)": "L",
        "Choosing Data Structures": "A",
        "Basic file system abstraction and navigation (folders, paths)": "L",
        "Basic programming in any language (variables, control flow, functions)": "C",
        "Basic Python": "C",
        "Building and using JSON APIs": "L",
        "Debugging Strategies": "A",
        "Functions as parameters (sort, map)": "L",
        "Github (distributed source control)": "A",
        "HTTP": "A",
        "List Comprehension": "L",
        "Nested Data": "L",
        "Efficiently learn a new API/Software Library": "L",
        "Problem Solving Strategies": "A",
        "Source code documentation and repository best practices": "A",
        "Unit Tests": "A",
        "Unix command line": "A",
        "Variable scope": "L"
      }
    },
    "Data-Oriented Programming": {
      "courseID":"SI 206",
      "Pre-reqs": {
        "Text: standard formats (CSV)": "A",
        "Choosing Data Structures": "A",
        "Be able to develop a plan to address complex or ambiguous problems": "A",
        "Basic file system abstraction and navigation (folders, paths)": "A",
        "Basic programming in any language (variables, control flow, functions)": "L",
        "Basic Python": "L",
        "Building and using JSON APIs": "L",
        "Debugging Strategies": "A",
        "Functions as parameters (sort, map)": "A",
        "Information organization": "A",
        "Installing a python development environment  ": "A",
        "Nested Data": "L",
        "OOP development": "A",
        "Problem Solving Strategies": "L",
        "Unit Tests": "A",
        "Unix command line": "A",
        "Variable scope": "L"
      },
      "Outcomes": {
        "Describe, predict, and effectively leverage the implications of technical/social design decisions for online community/social/interpersonal dynamics": "A",
        "Images/Video/Audio (familiarity with data formats and processing libraries)": "A",
        "Permutation and combination": "A",
        "Python data science libraries (pandas, numpy, scipy)": "A",
        "Text: NLP (libraries e.g. NLTK)": "A",
        "Text: standard formats (CSV)": "C",
        "Visualization methods": "A",
        "Choosing Data Structures": "L",
        "Databases (understanding schema, libraries to access)": "L",
        "SQL": "A",
        "Be able to develop a plan to address complex or ambiguous problems": "L",
        "Dealing with inherent ambiguity": "A",
        "Basic file system abstraction and navigation (folders, paths)": "L",
        "Basic programming in any language (variables, control flow, functions)": "C",
        "Basic Python": "C",
        "Building and using JSON APIs": "C",
        "Debugging Strategies": "L",
        "Efficiency Profiling": "A",
        "Frontend development": "A",
        "Functions as parameters (sort, map)": "C",
        "Github (distributed source control)": "L",
        "HTML and CSS": "A",
        "HTTP": "A",
        "Installing a python development environment  ": "L",
        "List Comprehension": "L",
        "Nested Data": "C",
        "Efficiently learn a new API/Software Library": "C",
        "OO Development: Subclassing": "C",
        "Open Source Software:collaborational licenses  ": "A",
        "Pattern matching (regular expressions / Regex)": "L",
        "Problem Solving Strategies": "L",
        "Source code documentation and repository best practices": "L",
        "Unit Tests": "L",
        "Unix command line": "L",
        "Variable scope": "C"
      }
    },
    "Models of Social Information Processing": {
      "ID":{"SI 301"},
      "Pre-reqs": {
        "Linear models: linear regression": "L",
        "Mean, variance, median, standard devices": "C",
        "Python data science libraries (pandas, numpy, scipy)": "A",
        "Computing simple probabilities ": "C",
        "Write Short  Essays ": "L",
        "Basic file system abstraction and navigation (folders, paths)": "L",
        "Basic programming in any language (variables, control flow, functions)": "C",
        "Basic Python": "C",
        "Debugging Strategies": "A",
        "Statistical analysis": "L"
      },
      "Outcomes": {
        "Build and maintain relationships through social media": "L",
        "Social media metrics (e.g., reach, engagement, impressions, share of voice, sentiment, ROI, etc.)": "L",
        "Describe, predict, and effectively leverage the implications of technical/social design decisions for online community/social/interpersonal dynamics": "A",
        "Design and optimize social media campaigns": "L",
        "Determine the set of social media features/affordances needed for a particular organization, team, community,  or project": "L",
        "Clustering": "L",
        "Data Types: creating, parsing": "L",
        "Network data (statistics, libraries e.g. NetworkX)": "C",
        "Visualization methods": "C",
        "Applying Bayes' Theorem": "C",
        "Auctions": "L",
        "Behavioral economics": "L",
        "Game theory ": "L",
        "Matching markets ": "L",
        "Models of  information diffusion on networks": "C",
        "Models of consumer preferences ": "L",
        "Choosing Data Structures": "L",
        "Explain Important Concepts Related To Study Of Information": "L",
        "Theory: Nash equalibrium, Subgame perfect equilibrium": "L",
        "Write engaging social media content": "L",
        "Write Short  Essays ": "C",
        "Rapid understanding and expression": "C",
        "Presentation/demonstration (prepared)": "L",
        "Project management": "L",
        "Team work / effective group collaboration": "L",
        "Technical writing": "L",
        "Presentation skills": "L",
        "Source code documentation and repository best practices": "L",
        "A/B testing": "L",
        "Formal usability evaluation(peer critque)": "L",
        "Make design decision and understand their implication": "L",
        "Social science theories that speak to online community/communication (e.g., models of diffusion, social capital, downwards comparison, etc. ) ": "C",
        "Surveys": "L",
        "Think aloud / experiments": "L",
        "Usability and ux questionaire/scales (SUS, SUPR-Q)": "L",
        "Human behavior ": "L"
      }
    },
    "Information Environments and Work": {
      "courseID":"310",
      "Pre-reqs": {},
      "Outcomes": {
        "Build and maintain relationships through social media": "A",
        "Describe, predict, and effectively leverage the implications of technical/social design decisions for online community/social/interpersonal dynamics": "A",
        "Determine the set of social media features/affordances needed for a particular organization, team, community,  or project": "A",
        "Advertising ": "L",
        "Applied Machine Learning": "A",
        "Crowdsourcing": "A",
        "Data Types: creating, parsing": "A",
        "Behavioral economics": "L",
        "Game theory ": "A",
        "Information theory": "A",
        "Models of consumer preferences ": "A",
        "Principles of Info Economics": "A",
        "Theory of the firm": "L",
        "Key metrics and ratios in financial reporting": "L",
        "Financial and cost accounting": "L",
        "Principal-Agent Theory (agency)": "C",
        "People: individual and group issues": "C",
        "Negotiating value (e.g. salary)": "L",
        "Choosing Data Structures": "A",
        "Ethics Of Info Use and Behavior ": "L",
        "Explain Important Concepts Related To Study Of Information": "A",
        "Opportunities in information professions": "A",
        "Reflect Critically On Own Use Of Info System": "L",
        "Information organization": "A",
        "Write and present for professional contexts (e.g., client reports, presentations)": "C",
        "Write engaging social media content": "A",
        "Write for research-oriented audiences": "A",
        "Write Short  Essays ": "C",
        "Rapid understanding and expression": "C",
        "Be able to develop a plan to address complex or ambiguous problems": "C",
        "Classification and Curation ": "A",
        "Creating compelling deliverables (Creating Hi-Fi prototype in UX)  ": "A",
        "Identifying potential problems early": "L",
        "Presentation/demonstration (prepared)": "L",
        "Professional communication (with clients)": "A",
        "Project management": "L",
        "Project scheduling, tracking": "A",
        "Team work / effective group collaboration": "L",
        "Technical writing": "L",
        "Team dynamics and conflict resolution": "L",
        "Time/quality engineering tradeoffs": "C",
        "Rapid prototyping": "L",
        "Stakeholders and interests in context": "C",
        "Requirements analysis and specification": "L",
        "Ambiguity and disambiguation (lexical and contextual)": "C",
        "Dealing with inherent ambiguity": "C",
        "Presentation skills": "L",
        "Calibrating effects of technical change": "C",
        "Managing tradeoffs": "C",
        "Professionalism in the workplace": "C",
        "Infrastructure, general and information, and why important": "C",
        "Infrastructure inversion": "C",
        "Leadership": "C",
        "Using history to construct context": "C",
        "Triage": "C",
        "Role of theory in practice": "C",
        "Speed of change (sources and coping skills)": "C",
        "List Comprehension": "A",
        "Problem Solving Strategies": "A",
        "Software engineering principles": "L",
        "Common HCI Lexicon (Design of Everyday Things) / Don Norman's": "A",
        "Motivation & Human Needs": "A",
        "User-centered design process": "A",
        "A/B testing": "A",
        "Cognitive walkthroughs": "A",
        "Formulate solid recommendations": "A",
        "Interviews": "A",
        "Make design decision and understand their implication": "L",
        "Prototype testing": "A",
        "Social science theories that speak to online community/communication (e.g., models of diffusion, social capital, downwards comparison, etc. ) ": "A",
        "Human behavior ": "A",
        "Contextual inquiry": "A",
        "Ideation / brainstorming": "A",
        "Needs assessment": "L",
        "Personas": "A",
        "Requirements definition": "L",
        "Scenarios": "A",
        "Sketches": "A",
        "Visual design": "A",
        "Wireframes": "A",
        "Participatory deslgn": "A"
      }
    }
  },
    "Career and Internship Studio": {
      "courseID": "SI 300",
      "Pre-reqs": {
        "Write and present for professional contexts (e.g., client reports, presentations)": "L",
        "Be able to develop a plan to address complex or ambiguous problems": "A",
        "Presentation/demonstration (prepared)": "L",
        "Professional communication (with clients)": "L",
        "Project management": "A",
        "Team dynamics and conflict resolution": "A",
        "Successfully powering through failure": "A",
        "Embracing life outside of the comfort zone": "A"
      }
      "Outcomes": {},
    },

    "Building Interactive Applications": {
      "courseID": "SI 364",
      "Pre-reqs": {
        "Data Types: creating, parsing": "L",
        "Exploratory data analysis to extract meaning from unfamiliar datasets": "A",
        "Text: standard formats (CSV)": "L",
        "Choosing Data Structures": "L",
        "Databases (understanding schema, libraries to access)": "L",
        "Relational Database Design": "A",
        "SQL": "A",
        "Be able to develop a plan to address complex or ambiguous problems": "A",
        "Basic file system abstraction and navigation (folders, paths)": "L",
        "Basic programming in any language (variables, control flow, functions)": "C",
        "Basic Python": "C",
        "Building and using JSON APIs": "L",
        "Debugging Strategies": "L",
        "Functions as parameters (sort, map)": "L",
        "Github (distributed source control)": "A",
        "HTML and CSS": "A",
        "HTTP": "A",
        "Nested Data": "L",
        "Efficiently learn a new API/Software Library": "A",
        "OO Development: Subclassing": "L",
        "OOP development": "A",
        "Pattern matching (regular expressions / Regex)": "A",
        "PHP Programming": "A",
        "Problem Solving Strategies": "L",
        "Unit Tests": "L",
        "Unix command line": "L",
        "Variable scope": "C",
        "Web development": "A"
      },
      "Outcomes": {
        "Choosing Data Structures": "L",
        "Databases (understanding schema, libraries to access)": "L",
        "Relational Database Design": "C",
        "SQL": "L",
        "Be able to develop a plan to address complex or ambiguous problems": "L",
        "Identifying potential problems early": "A",
        "Application Frameworks (e.g. Microsoft.net- fill in templates for different events)": "A",
        "Basic file system abstraction and navigation (folders, paths)": "C",
        "Building and using JSON APIs": "C",
        "Debugging Strategies": "C",
        "Event Handlers, Callbacks, decorators": "L",
        "Frontend development": "A",
        "Github (distributed source control)": "L",
        "HTML and CSS": "A",
        "HTTP": "C",
        "Information organization": "C",
        "JavaScript Programming": "L",
        "JQuery": "A",
        "Mobile development": "A",
        "Multimedia content": "L",
        "Efficiently learn a new API/Software Library": "L",
        "PHP Programming": "L",
        "Problem Solving Strategies": "C",
        "Responsive UI": "A",
        "Web development": "C",
        "Design guidelines": "A",
        "UX Design patterns": "A",
        "Ideation / brainstorming": "L",
        "Interaction design": "A"
      }
    },
    "Putting the H in HCI: Human Perception, Cognition and Mental Processes": {
      "courseID": "SI 388",
      "Pre-reqs": {
        "Improvised debrief (no preparation)": "A",
        "Presentation/demonstration (prepared)": "A",
        "Technical writing": "A",
        "Team dynamics and conflict resolution": "A",
        "Ideation / brainstorming": "A"
      },
      "Outcomes": {
        "Write and present for professional contexts (e.g., client reports, presentations)": "A",
        "Identifying potential problems early": "L",
        "Improvised debrief (no preparation)": "C",
        "Presentation/demonstration (prepared)": "L",
        "Team work / effective group collaboration": "L",
        "Technical writing": "L",
        "Team dynamics and conflict resolution": "L",
        "Anthropometrics": "L",
        "Common HCI Lexicon (Design of Everyday Things) / Don Norman's": "C",
        "Design principles (e.g. Gestalt, visual grouping, HCI 'laws')": "C",
        "Emotional design / levels of emotional processing & the 3 brains": "A",
        "Etiquette, Politeness, Consideration / Reeves & Nass, Grice, Cooper": "L",
        "Human responsiveness thresholds": "A",
        "Memory capabilities & limitations": "C",
        "Mental Representations & Problem Solving cog sci theories": "L",
        "Motivation & Human Needs": "L",
        "Skill acquisition & Learning processes cog sci theories": "A",
        "Text comprehension principles": "A",
        "Usability heuristics": "L",
        "UX Design patterns": "A",
        "Formal usability evaluation(peer critque)": "L",
        "Heuristic evaluation": "C",
        "Make design decision and understand their implication": "L",
        "Accessibility Reviews (Universal Design)": "C",
        "Ideation / brainstorming": "L",
        "Interaction design": "A",
        "Needs assessment": "A",
        "Personas": "A"
      }
    },
    "Needs Assessment and Usability Evaluation": {
      "courseID": "SI 422",
      "Pre-reqs": {
        "Project management": "A",
        "Project scheduling, tracking": "A",
        "Team work / effective group collaboration": "A",
        "Technical writing": "L",
        "Design guidelines": "A",
        "User-centered design process": "A",
        "Competititve analysis": "A"
      },
      "Outcomes": {
        "Write and present for professional contexts (e.g., client reports, presentations)": "L",
        "Project management": "L",
        "Project scheduling, tracking": "L",
        "Team work / effective group collaboration": "L",
        "Technical writing": "C",
        "Common HCI Lexicon (Design of Everyday Things) / Don Norman's": "L",
        "Design principles (e.g. Gestalt, visual grouping, HCI 'laws')": "A",
        "Etiquette, Politeness, Consideration / Reeves & Nass, Grice, Cooper": "A",
        "Human responsiveness thresholds": "A",
        "Memory capabilities & limitations": "A",
        "Motivation & Human Needs": "A",
        "Text comprehension principles": "A",
        "Usability heuristics": "C",
        "User-centered design process": "L",
        "UX Design patterns": "A",
        "A/B testing": "C",
        "Articulate arguments relating to information policy": "A",
        "Cognitive walkthroughs": "A",
        "Experiment design(A/B testing) ": "C",
        "Formal usability evaluation(peer critque)": "A",
        "Formulate solid recommendations": "C",
        "Heuristic evaluation": "C",
        "Interviews": "C",
        "Make design decision and understand their implication": "A",
        "Prototype testing": "C",
        "Statistical analysis": "L",
        "Study design": "C",
        "Surveys": "C",
        "Think aloud / experiments": "C",
        "Usability and ux questionaire/scales (SUS, SUPR-Q)": "L",
        "Usability testing": "C",
        "Accessibility Reviews (Universal Design)": "A",
        "Competititve analysis": "C",
        "Contextual inquiry": "A",
        "Design space analysis": "A",
        "Digital prototyping tools": "A",
        "Hi-fidelity prototypes": "A",
        "Ideation / brainstorming": "L",
        "Interaction design": "A",
        "Lo-fidelity prototypes": "C",
        "Needs assessment": "C",
        "Personas": "C",
        "Requirements definition": "A",
        "Scenarios": "C",
        "Sketches": "L",
        "Story boards": "A",
        "Visual design": "A",
        "Wireframes": "A"
      }
    },
    "Interaction Design Studio": {
      "courseID": "SI 482",
      "Pre-reqs": {
        "Ethics Of Info Use and Behavior ": "A",
        "Explain Important Concepts Related To Study Of Information": "A",
        "Write and present for professional contexts (e.g., client reports, presentations)": "A",
        "Be able to develop a plan to address complex or ambiguous problems": "A",
        "Creating compelling deliverables (Creating Hi-Fi prototype in UX)  ": "A",
        "Presentation/demonstration (prepared)": "A",
        "Common HCI Lexicon (Design of Everyday Things) / Don Norman's": "A",
        "Usability heuristics": "A",
        "UX Design patterns": "A",
        "Heuristic evaluation": "A",
        "Think aloud / experiments": "A",
        "Usability and ux questionaire/scales (SUS, SUPR-Q)": "A",
        "Usability testing": "A",
        "Contextual inquiry": "A",
        "Needs assessment": "A"
      },
      "Outcomes ": {
        "Ethics Of Info Use and Behavior ": "A",
        "Explain Important Concepts Related To Study Of Information": "A",
        "Write and present for professional contexts (e.g., client reports, presentations)": "L",
        "Be able to develop a plan to address complex or ambiguous problems": "L",
        "Creating compelling deliverables (Creating Hi-Fi prototype in UX)  ": "C",
        "Identifying potential problems early": "L",
        "Presentation/demonstration (prepared)": "C",
        "Professional communication (with clients)": "A",
        "Project management": "L",
        "Project scheduling, tracking": "A",
        "Team work / effective group collaboration": "L",
        "Technical writing": "A",
        "Team dynamics and conflict resolution": "L",
        "Time/quality engineering tradeoffs": "L",
        "Frontend development": "A",
        "HTML and CSS": "A",
        "JavaScript Programming": "A",
        "JQuery": "A",
        "Mobile development": "A",
        "Multimedia content": "A",
        "Responsive UI": "A",
        "Web development": "A",
        "Common HCI Lexicon (Design of Everyday Things) / Don Norman's": "L",
        "Design guidelines": "L",
        "Design principles (e.g. Gestalt, visual grouping, HCI 'laws')": "C",
        "Human responsiveness thresholds": "A",
        "Memory capabilities & limitations": "A",
        "Mental Representations & Problem Solving cog sci theories": "A",
        "Motivation & Human Needs": "A",
        "Skill acquisition & Learning processes cog sci theories": "A",
        "Text comprehension principles": "A",
        "Usability heuristics": "L",
        "User-centered design process": "C",
        "UX Design patterns": "L",
        "A/B testing": "A",
        "Cognitive walkthroughs": "C",
        "Experiment design(A/B testing) ": "A",
        "Formal usability evaluation(peer critque)": "C",
        "Formulate solid recommendations": "L",
        "Heuristic evaluation": "L",
        "Make design decision and understand their implication": "L",
        "Prototype testing": "C",
        "Study design": "A",
        "Surveys": "A",
        "Think aloud / experiments": "A",
        "Usability testing": "L",
        "Human behavior ": "L",
        "Competititve analysis": "C",
        "Contextual inquiry": "A",
        "Design space analysis": "C",
        "Design synthesis": "C",
        "Digital prototyping tools": "C",
        "Hi-fidelity prototypes": "C",
        "Ideation / brainstorming": "C",
        "Interaction design": "C",
        "Lo-fidelity prototypes": "C",
        "Needs assessment": "L",
        "Personas": "L",
        "Requirements definition": "L",
        "Scenarios": "L",
        "Sketches": "C",
        "Story boards": "C",
        "Visual design": "L",
        "Wireframes": "C"
      }
    },
    "User Experience Final Project": {
      "courseID": "SI 487",
      "Pre-reqs": {
        "Describe, predict, and effectively leverage the implications of technical/social design decisions for online community/social/interpersonal dynamics": "A",
        "Crowdsourcing": "A",
        "Exploratory data analysis to extract meaning from unfamiliar datasets": "A",
        "Familiar with statistical package: Stata, R, SPSS": "L",
        "Images/Video/Audio (familiarity with data formats and processing libraries)": "L",
        "Independent and dependent variables: dummy variables ": "L",
        "Mean, variance, median, standard devices": "L",
        "Qualitative methods": "L",
        "T-test, wilcoxon rank sum test": "L",
        "Tableau ": "A",
        "Visualization methods": "A",
        "Behavioral economics": "A",
        "Game theory ": "A",
        "Information theory": "A",
        "Models of consumer preferences ": "A",
        "Choosing Data Structures": "A",
        "Databases (understanding schema, libraries to access)": "A",
        "Relational Database Design": "A",
        "SQL": "A",
        "Ethics Of Info Use and Behavior ": "C",
        "Explain Important Concepts Related To Study Of Information": "L",
        "Relating Info Frame to Multiple Domains": "C",
        "Write and present for professional contexts (e.g., client reports, presentations)": "L",
        "Be able to develop a plan to address complex or ambiguous problems": "A",
        "Creating compelling deliverables (Creating Hi-Fi prototype in UX)  ": "L",
        "Improvised debrief (no preparation)": "L",
        "Presentation/demonstration (prepared)": "L",
        "Professional communication (with clients)": "A",
        "Project management": "A",
        "Project scheduling, tracking": "A",
        "Team work / effective group collaboration": "L",
        "Technical writing": "C",
        "Team dynamics and conflict resolution": "L",
        "Time/quality engineering tradeoffs": "A",
        "Application Frameworks (e.g. Microsoft.net- fill in templates for different events)": "A",
        "Basic file system abstraction and navigation (folders, paths)": "A",
        "Basic programming in any language (variables, control flow, functions)": "C",
        "Basic Python": "C",
        "Building and using JSON APIs": "L",
        "Event Handlers, Callbacks, decorators": "A",
        "Frontend development": "C",
        "HTML and CSS": "L",
        "HTTP": "A",
        "Information organization": "L",
        "Installing a python development environment  ": "A",
        "JavaScript Programming": "C",
        "JQuery": "A",
        "Mobile development": "L",
        "Multimedia content": "L",
        "Efficiently learn a new API/Software Library": "C",
        "Pattern matching (regular expressions / Regex)": "L",
        "PHP Programming": "A",
        "Problem Solving Strategies": "C",
        "Responsive UI": "L",
        "Web development": "C",
        "Common HCI Lexicon (Design of Everyday Things) / Don Norman's": "C",
        "Credibility & Persuasion / Fogg": "A",
        "Design guidelines": "L",
        "Design principles (e.g. Gestalt, visual grouping, HCI 'laws')": "C",
        "Emotional design / levels of emotional processing & the 3 brains": "A",
        "Etiquette, Politeness, Consideration / Reeves & Nass, Grice, Cooper": "A",
        "Human responsiveness thresholds": "L",
        "Memory capabilities & limitations": "L",
        "Mental Representations & Problem Solving cog sci theories": "L",
        "Motivation & Human Needs": "L",
        "Skill acquisition & Learning processes cog sci theories": "A",
        "Text comprehension principles": "A",
        "Usability heuristics": "C",
        "User-centered design process": "C",
        "UX Design patterns": "L",
        "A/B testing": "L",
        "Cognitive walkthroughs": "L",
        "Experiment design(A/B testing) ": "L",
        "Formal usability evaluation(peer critque)": "L",
        "Formulate solid recommendations": "L",
        "Heuristic evaluation": "L",
        "Interviews": "L",
        "Make design decision and understand their implication": "L",
        "Prototype testing": "L",
        "Statistical analysis": "C",
        "Study design": "L",
        "Surveys": "L",
        "Think aloud / experiments": "L",
        "Usability and ux questionaire/scales (SUS, SUPR-Q)": "L",
        "Usability testing": "L",
        "Competititve analysis": "C",
        "Contextual inquiry": "L",
        "Design space analysis": "L",
        "Design synthesis": "L",
        "Digital prototyping tools": "C",
        "Hi-fidelity prototypes": "L",
        "Ideation / brainstorming": "L",
        "Interaction design": "C",
        "Lo-fidelity prototypes": "L",
        "Needs assessment": "L",
        "Personas": "L",
        "Requirements definition": "L",
        "Scenarios": "L",
        "Sketches": "L",
        "Story boards": "L",
        "Visual design": "L",
        "Wireframes": "L"
      },
      "Outcomes": {
        "Design and optimize social media campaigns": "A",
        "Images/Video/Audio (familiarity with data formats and processing libraries)": "A",
        "Visualization methods": "A",
        "Write and present for professional contexts (e.g., client reports, presentations)": "A",
        "Write Short  Essays ": "A",
        "Be able to develop a plan to address complex or ambiguous problems": "L",
        "Creating compelling deliverables (Creating Hi-Fi prototype in UX)  ": "C",
        "Presentation/demonstration (prepared)": "L",
        "Professional communication (with clients)": "L",
        "Project management": "L",
        "Project scheduling, tracking": "C",
        "Team work / effective group collaboration": "A",
        "Information organization": "L",
        "Design guidelines": "L",
        "Design principles (e.g. Gestalt, visual grouping, HCI 'laws')": "L",
        "Emotional design / levels of emotional processing & the 3 brains": "L",
        "Make design decision and understand their implication": "L",
        "Digital prototyping tools": "C",
        "Hi-fidelity prototypes": "C",
        "Ideation / brainstorming": "L",
        "Needs assessment": "L",
        "Visual design": "C"
      }
    },
    "Graphic Design": {
      "courseID": "SI 320",
      "Pre-reqs": {
        "Basic file system abstraction and navigation (folders, paths)": "A",
        "Frontend development": "A",
        "Github (distributed source control)": "A",
        "Information organization": "A",
        "Multimedia content": "A",
        "Responsive UI": "A",
        "Web development": "A",
        "UX Design patterns": "A",
        "Prototype testing": "A",
        "Competititve analysis": "A",
        "Digital prototyping tools": "A",
        "Ideation / brainstorming": "A",
        "Interaction design": "A",
        "Lo-fidelity prototypes": "L",
        "Needs assessment": "A",
        "Personas": "A",
        "Requirements definition": "A",
        "Scenarios": "A",
        "Sketches": "A",
        "Story boards": "A",
        "Wireframes": "A"
      },
      "Outcomes": {
        "Design and optimize social media campaigns": "A",
        "Images/Video/Audio (familiarity with data formats and processing libraries)": "A",
        "Visualization methods": "A",
        "Write and present for professional contexts (e.g., client reports, presentations)": "A",
        "Write Short  Essays ": "A",
        "Be able to develop a plan to address complex or ambiguous problems": "L",
        "Creating compelling deliverables (Creating Hi-Fi prototype in UX)  ": "C",
        "Presentation/demonstration (prepared)": "L",
        "Professional communication (with clients)": "L",
        "Project management": "L",
        "Project scheduling, tracking": "C",
        "Team work / effective group collaboration": "A",
        "Information organization": "L",
        "Design guidelines": "L",
        "Design principles (e.g. Gestalt, visual grouping, HCI 'laws')": "L",
        "Emotional design / levels of emotional processing & the 3 brains": "L",
        "Make design decision and understand their implication": "L",
        "Digital prototyping tools": "C",
        "Hi-fidelity prototypes": "C",
        "Ideation / brainstorming": "L",
        "Needs assessment": "L",
        "Visual design": "C"
      }
    },
    "Web Design, Development, and Accessibiility": {
      "courseID": "SI 339",
      "Pre-reqs": {
        "Text: standard formats (CSV)": "L",
        "Basic file system abstraction and navigation (folders, paths)": "C",
        "Basic programming in any language (variables, control flow, functions)": "C",
        "Basic Python": "L",
        "Debugging Strategies": "A"
      },
      "Outcomes": {
        "Debugging Strategies": "L",
        "Frontend development": "C",
        "HTML and CSS": "C",
        "HTTP": "C",
        "JavaScript Programming": "L",
        "JQuery": "L",
        "Multimedia content": "L",
        "Problem Solving Strategies": "C",
        "Responsive UI": "C",
        "Variable scope": "L",
        "Web development": "C",
        "Design principles (e.g. Gestalt, visual grouping, HCI 'laws')": "L",
        "User-centered design process": "L",
        "Sketches": "L",
        "Visual design": "L",
        "Wireframes": "L"
      }
    },
    "Experiment Design and Analyses": {
      "courseID": "SI 340",
      "Pre-reqs": {},
      "Outcomes": {
        "Write and present for professional contexts (e.g., client reports, presentations)": "L",
        "Write engaging social media content": "L",
        "Write for research-oriented audiences": "L",
        "Presentation/demonstration (prepared)": "C",
        "Project management": "L",
        "Technical writing": "L",
        "Team dynamics and conflict resolution": "L",
        "Credibility & Persuasion / Fogg": "L",
        "Mental Representations & Problem Solving cog sci theories": "L",
        "Motivation & Human Needs": "M",
        "Experiment design(A/B testing) ": "M",
        "Heuristic evaluation": "C",
        "Social science theories that speak to online community/communication (e.g., models of diffusion, social capital, downwards comparison, etc. ) ": "M",
        "Study design": "C",
        "Surveys": "C",
        "Usability and ux questionaire/scales (SUS, SUPR-Q)": "C",
        "Usability testing": "C",
        "Competititve analysis": "L",
        "Interaction design": "C"
      }
    },
    "Cyberscience": {
      "courseID": "SI 365",
      "Pre-reqs": {},
      "Outcomes": {
        "Design principles (e.g. Gestalt, visual grouping, HCI 'laws')": "C"
      }
    },
    "Information Technology and Global Soceity": {
      "courseID": "SI 430",
      "Pre-reqs": {},
      "Outcomes": {}
    }
  },
  "IA": {
    "Data Manipulation": {
      "courseID": "SI 330",
      "Pre-reqs": {
        "Databases (understanding schema, libraries to access)": "A",
        "SQL": "A",
        "Basic file system abstraction and navigation (folders, paths)": "C",
        "Basic programming in any language (variables, control flow, functions)": "C",
        "Basic Python": "L",
        "Building and using JSON APIs": "L",
        "Installing a python development environment  ": "A",
        "List Comprehension": "A",
        "Pattern matching (regular expressions / Regex)": "L",
        "Writing code in terms of vector ops / high-level data structure ": "L"
      },
      "Outcomes ": {
        "Big Data (computing with large-scale datasets)": "L",
        "Data Types: creating, parsing": "L",
        "Exploratory data analysis to extract meaning from unfamiliar datasets": "A",
        "Network data (statistics, libraries e.g. NetworkX)": "A",
        "Python data science libraries (pandas, numpy, scipy)": "A",
        "Text: NLP (libraries e.g. NLTK)": "A",
        "Text: standard formats (CSV)": "L",
        "Visualization methods": "A",
        "Choosing Data Structures": "A",
        "Databases (understanding schema, libraries to access)": "L",
        "SQL": "L",
        "Write and present for professional contexts (e.g., client reports, presentations)": "L",
        "Creating compelling deliverables (Creating Hi-Fi prototype in UX)  ": "L",
        "Presentation/demonstration (prepared)": "A",
        "Project scheduling, tracking": "A",
        "Technical writing": "A",
        "Time/quality engineering tradeoffs": "A",
        "Debugging Strategies": "A",
        "Functions as parameters (sort, map)": "L",
        "Github (distributed source control)": "A",
        "Large-scale computation (Hadoop, Spark)": "L",
        "Efficiently learn a new API/Software Library": "L",
        "OO Development: Subclassing": "A",
        "OOP development": "A",
        "Pattern matching (regular expressions / Regex)": "C",
        "Problem Solving Strategies": "A",
        "Source code documentation and repository best practices": "A",
        "Unit Tests": "A",
        "Unix command line": "A",
        "Variable scope": "L"
      }
    },
    "Data Exploration": {
      "courseID": "SI 370",
      "Pre-reqs": {
        "Linear models: linear regression": "A",
        "Python data science libraries (pandas, numpy, scipy)": "A"
      },
      "Outcomes": {
        "Applied Machine Learning": "L",
        "Clustering": "L",
        "Exploratory data analysis to extract meaning from unfamiliar datasets": "C",
        "Linear models: linear regression": "C",
        "Network data (statistics, libraries e.g. NetworkX)": "L",
        "PCA/Factor Analysis": "L",
        "Python data science libraries (pandas, numpy, scipy)": "C",
        "Tableau ": "L",
        "Text: NLP (libraries e.g. NLTK)": "L",
        "Text: standard formats (CSV)": "C",
        "Visualization methods": "C",
        "Functions as parameters (sort, map)": "C",
        "Efficiently learn a new API/Software Library": "C",
        "Problem Solving Strategies": "L"
      }
    },
    "Introduction to User Modeling": {
      "courseID": "SI 425",
      "Pre-reqs": {},
      "Outcomes": {
        "Applied Machine Learning": "A",
        "Big Data (computing with large-scale datasets)": "L",
        "Clustering": "L",
        "Crowdsourcing": "A",
        "Exploratory data analysis to extract meaning from unfamiliar datasets": "C",
        "Linear models: linear regression": "L",
        "Qualitative methods": "A",
        "Text: NLP (libraries e.g. NLTK)": "L",
        "Visualization methods": "L",
        "Auctions": "L",
        "Behavioral economics": "L",
        "Game theory ": "L",
        "Matching markets ": "L",
        "Models of  information diffusion on networks": "C",
        "Models of consumer preferences ": "L",
        "Identifying potential problems early": "L",
        "Project scheduling, tracking": "C",
        "HTML and CSS": "L"
      }
    },
    "Information Analysis Final Project Preparation Course": {
      "courseID": "SI 405",
      "Pre-reqs": {},
      "Outcomes": {
        "Write and present for professional contexts (e.g., client reports, presentations)": "A",
        "Be able to develop a plan to address complex or ambiguous problems": "L",
        "Identifying potential problems early": "A",
        "Improvised debrief (no preparation)": "L",
        "Presentation/demonstration (prepared)": "L",
        "Professional communication (with clients)": "L",
        "Project management": "L",
        "Project scheduling, tracking": "L",
        "Team work / effective group collaboration": "L",
        "Technical writing": "A",
        "Team dynamics and conflict resolution": "A",
        "Time/quality engineering tradeoffs": "L"
      }
    },
    "Information Analytics Project": {
      "courseID": "SI 485",
      "Pre-reqs": {
        "Applied Machine Learning": "L",
        "Big Data (computing with large-scale datasets)": "L",
        "Causal inference (IV, propensity score matching)": "A",
        "Clustering": "C",
        "Crowdsourcing": "L",
        "Data Types: creating, parsing": "C",
        "Exploratory data analysis to extract meaning from unfamiliar datasets": "C",
        "Familiar with statistical package: Stata, R, SPSS": "A",
        "Images/Video/Audio (familiarity with data formats and processing libraries)": "A",
        "Independent and dependent variables: dummy variables ": "L",
        "Linear models: linear regression": "C",
        "Generalized linear models: logit and probit ": "C",
        "Mean, variance, median, standard devices": "C",
        "Network data (statistics, libraries e.g. NetworkX)": "L",
        "PCA/Factor Analysis": "L",
        "Permutation and combination": "A",
        "Python data science libraries (pandas, numpy, scipy)": "C",
        "Qualitative methods": "A",
        "T-test, wilcoxon rank sum test": "L",
        "Tableau ": "A",
        "Text: NLP (libraries e.g. NLTK)": "A",
        "Text: standard formats (CSV)": "C",
        "Visualization methods": "C",
        "Choosing Data Structures": "L",
        "Databases (understanding schema, libraries to access)": "L",
        "Relational Database Design": "L",
        "SQL": "L",
        "Ethics Of Info Use and Behavior ": "A",
        "Explain Important Concepts Related To Study Of Information": "L",
        "Opportunities in information professions": "A",
        "Reflect Critically On Own Use Of Info System": "L",
        "Write and present for professional contexts (e.g., client reports, presentations)": "L",
        "Be able to develop a plan to address complex or ambiguous problems": "L",
        "Identifying potential problems early": "A",
        "Improvised debrief (no preparation)": "L",
        "Presentation/demonstration (prepared)": "L",
        "Professional communication (with clients)": "L",
        "Project management": "L",
        "Project scheduling, tracking": "L",
        "Team work / effective group collaboration": "L",
        "Technical writing": "A",
        "Time/quality engineering tradeoffs": "L",
        "Application Frameworks (e.g. Microsoft.net- fill in templates for different events)": "L",
        "Basic file system abstraction and navigation (folders, paths)": "C",
        "Basic programming in any language (variables, control flow, functions)": "C",
        "Basic Python": "C",
        "Building and using JSON APIs": "A",
        "Debugging Strategies": "L",
        "Efficiency Profiling": "A",
        "Full stack (unix sysadmin)": "L",
        "Github (distributed source control)": "L",
        "HTML and CSS": "C",
        "HTTP": "L",
        "Information organization": "L",
        "Installing a python development environment  ": "L",
        "JavaScript Programming": "L",
        "JQuery": "A",
        "Large-scale computation (Hadoop, Spark)": "L",
        "Efficiently learn a new API/Software Library": "L",
        "OO Development: Subclassing": "A",
        "OOP development": "A",
        "Open Source Software:collaborational licenses  ": "A",
        "Pattern matching (regular expressions / Regex)": "C",
        "Problem Solving Strategies": "L",
        "Source code documentation and repository best practices": "L",
        "Unit Tests": "L",
        "Unix command line": "L",
        "Web development": "L",
        "Writing code in terms of vector ops / high-level data structure ": "C",
        "Formulate solid recommendations": "L",
        "Make design decision and understand their implication": "L"
      },
      "Outcomes": {
        "Applied Machine Learning": "C",
        "Big Data (computing with large-scale datasets)": "L",
        "Causal inference (IV, propensity score matching)": "L",
        "Clustering": "C",
        "Crowdsourcing": "C",
        "Data Types: creating, parsing": "C",
        "Exploratory data analysis to extract meaning from unfamiliar datasets": "C",
        "Familiar with statistical package: Stata, R, SPSS": "A",
        "Images/Video/Audio (familiarity with data formats and processing libraries)": "A",
        "Independent and dependent variables: dummy variables ": "C",
        "Linear models: linear regression": "C",
        "Generalized linear models: logit and probit ": "C",
        "Mean, variance, median, standard devices": "C",
        "Network data (statistics, libraries e.g. NetworkX)": "L",
        "PCA/Factor Analysis": "L",
        "Permutation and combination": "A",
        "Python data science libraries (pandas, numpy, scipy)": "C",
        "Qualitative methods": "L",
        "T-test, wilcoxon rank sum test": "L",
        "Tableau ": "L",
        "Text: NLP (libraries e.g. NLTK)": "L",
        "Text: standard formats (CSV)": "C",
        "Visualization methods": "C",
        "Choosing Data Structures": "C",
        "Databases (understanding schema, libraries to access)": "L",
        "Relational Database Design": "L",
        "SQL": "L",
        "Ethics Of Info Use and Behavior ": "L",
        "Explain Important Concepts Related To Study Of Information": "L",
        "Opportunities in information professions": "A",
        "Reflect Critically On Own Use Of Info System": "C",
        "Write and present for professional contexts (e.g., client reports, presentations)": "C",
        "Be able to develop a plan to address complex or ambiguous problems": "C",
        "Identifying potential problems early": "A",
        "Improvised debrief (no preparation)": "L",
        "Presentation/demonstration (prepared)": "C",
        "Professional communication (with clients)": "C",
        "Project management": "C",
        "Project scheduling, tracking": "C",
        "Team work / effective group collaboration": "C",
        "Technical writing": "L",
        "Time/quality engineering tradeoffs": "L",
        "Application Frameworks (e.g. Microsoft.net- fill in templates for different events)": "L",
        "Efficiency Profiling": "A",
        "Github (distributed source control)": "C",
        "HTML and CSS": "C",
        "Large-scale computation (Hadoop, Spark)": "L",
        "Efficiently learn a new API/Software Library": "C",
        "OO Development: Subclassing": "A",
        "Problem Solving Strategies": "C",
        "Source code documentation and repository best practices": "C",
        "Unit Tests": "L",
        "Web development": "L",
        "Writing code in terms of vector ops / high-level data structure ": "C",
        "Formulate solid recommendations": "L",
        "Make design decision and understand their implication": "C"
      }
    }
  },
  "Social Media": {
    "Interpersonal and Psychological Implications of Social Media": {
      "courseID": "SI 315",
      "Pre-reqs": {},
      "Outcomes": {
        "Describe, predict, and effectively leverage the implications of technical/social design decisions for online community/social/interpersonal dynamics": "L",
        "Design and optimize social media campaigns": "A",
        "Determine the set of social media features/affordances needed for a particular organization, team, community,  or project": "L"
      }
    },
    "Social Media in Organizations": {
      "courseID": "SI 335",
      "Pre-reqs": {
        "Design and optimize social media campaigns": "A",
        "Determine the set of social media features/affordances needed for a particular organization, team, community,  or project": "A",
        "Exploratory data analysis to extract meaning from unfamiliar datasets": "L",
        "Familiar with statistical package: Stata, R, SPSS": "L",
        "Mean, variance, median, standard devices": "L",
        "Information theory": "A",
        "Write and present for professional contexts (e.g., client reports, presentations)": "A",
        "Write Short  Essays ": "A",
        "Be able to develop a plan to address complex or ambiguous problems": "A",
        "Identifying potential problems early": "A",
        "Presentation/demonstration (prepared)": "A",
        "Team work / effective group collaboration": "A",
        "Technical writing": "A"
      },
      "Outcomes": {
        "Manage social media monitoring capabilities": "A",
        "Social media metrics (e.g., reach, engagement, impressions, share of voice, sentiment, ROI, etc.)": "A",
        "Statistical techniques to draw insights using data from social media": "A",
        "Describe, predict, and effectively leverage the implications of technical/social design decisions for online community/social/interpersonal dynamics": "L",
        "Design and optimize social media campaigns": "L",
        "Determine the set of social media features/affordances needed for a particular organization, team, community,  or project": "L",
        "Exploratory data analysis to extract meaning from unfamiliar datasets": "L",
        "Familiar with statistical package: Stata, R, SPSS": "L",
        "Mean, variance, median, standard devices": "L",
        "Write and present for professional contexts (e.g., client reports, presentations)": "L",
        "Write Short  Essays ": "L",
        "Be able to develop a plan to address complex or ambiguous problems": "L",
        "Identifying potential problems early": "L",
        "Presentation/demonstration (prepared)": "L",
        "Team work / effective group collaboration": "L",
        "Technical writing": "L"
      }
    },
    "Online Communities: Analysis and Design of Online Interaction": {
      "courseID": "SI 429",
      "Pre-reqs": {
        "Models of  information diffusion on networks": "A",
        "Event Handlers, Callbacks, decorators": "A"
      },
      "Outcomes": {
        "Manage social media monitoring capabilities": "A",
        "Social media metrics (e.g., reach, engagement, impressions, share of voice, sentiment, ROI, etc.)": "A",
        "Statistical techniques to draw insights using data from social media": "A",
        "Describe, predict, and effectively leverage the implications of technical/social design decisions for online community/social/interpersonal dynamics": "C",
        "Design and optimize social media campaigns": "L",
        "Determine the set of social media features/affordances needed for a particular organization, team, community,  or project": "C",
        "Write and present for professional contexts (e.g., client reports, presentations)": "C"
      }
    },
    "Designing Engagement Through Social Media": {
      "courseID": "SI 489",
      "Pre-reqs": {
        "Manage social media monitoring capabilities": "L",
        "Social media metrics (e.g., reach, engagement, impressions, share of voice, sentiment, ROI, etc.)": "L",
        "Statistical techniques to draw insights using data from social media": "L",
        "Describe, predict, and effectively leverage the implications of technical/social design decisions for online community/social/interpersonal dynamics": "L",
        "Design and optimize social media campaigns": "L",
        "Determine the set of social media features/affordances needed for a particular organization, team, community,  or project": "L",
        "Exploratory data analysis to extract meaning from unfamiliar datasets": "C",
        "Familiar with statistical package: Stata, R, SPSS": "C",
        "Mean, variance, median, standard devices": "C",
        "Network data (statistics, libraries e.g. NetworkX)": "C",
        "Qualitative methods": "C",
        "Information theory": "L",
        "Models of  information diffusion on networks": "L",
        "Ethics Of Info Use and Behavior ": "C",
        "Write and present for professional contexts (e.g., client reports, presentations)": "L",
        "Write engaging social media content": "L",
        "Be able to develop a plan to address complex or ambiguous problems": "L",
        "Identifying potential problems early": "L",
        "Presentation/demonstration (prepared)": "L",
        "Professional communication (with clients)": "L",
        "Project management": "L",
        "Project scheduling, tracking": "L",
        "Team work / effective group collaboration": "L",
        "Technical writing": "L"
      },
      "Outcomes": {
        "Manage social media monitoring capabilities": "C",
        "Social media metrics (e.g., reach, engagement, impressions, share of voice, sentiment, ROI, etc.)": "C",
        "Statistical techniques to draw insights using data from social media": "C",
        "Describe, predict, and effectively leverage the implications of technical/social design decisions for online community/social/interpersonal dynamics": "C",
        "Design and optimize social media campaigns": "C",
        "Determine the set of social media features/affordances needed for a particular organization, team, community,  or project": "C",
        "Exploratory data analysis to extract meaning from unfamiliar datasets": "C",
        "Familiar with statistical package: Stata, R, SPSS": "C",
        "Mean, variance, median, standard devices": "C",
        "Network data (statistics, libraries e.g. NetworkX)": "C",
        "Qualitative methods": "C",
        "Information theory": "C",
        "Models of  information diffusion on networks": "C",
        "Ethics Of Info Use and Behavior ": "C",
        "Write and present for professional contexts (e.g., client reports, presentations)": "C",
        "Write engaging social media content": "C",
        "Be able to develop a plan to address complex or ambiguous problems": "C",
        "Identifying potential problems early": "C",
        "Presentation/demonstration (prepared)": "C",
        "Professional communication (with clients)": "C",
        "Project management": "C",
        "Project scheduling, tracking": "C",
        "Team work / effective group collaboration": "C",
        "Technical writing": "C"
      }
    },
    "Designing and Analyzing Social Media Feeds": {
      "courseID": "SI 316",
      "Pre-reqs": {},
      "Outcomes": {
        "Describe, predict, and effectively leverage the implications of technical/social design decisions for online community/social/interpersonal dynamics": "L",
        "Determine the set of social media features/affordances needed for a particular organization, team, community,  or project": "L",
        "Participatory deslgn": "A"
      }
    },
    "Persuasion and Social Influence": {
      "courseID": "SI 334",
      "Pre-reqs": {},
      "Outcomes": {
        "Describe, predict, and effectively leverage the implications of technical/social design decisions for online community/social/interpersonal dynamics": "C",
        "Design and optimize social media campaigns": "L",
        "Determine the set of social media features/affordances needed for a particular organization, team, community,  or project": "A"
      }
    },
    "Succeeding at Failing": {
      "courseID": "SI 360",
      "Pre-reqs": {},
      "Outcomes": {
        "Game theory ": "A",
        "Ethics Of Info Use and Behavior ": "A",
        "Opportunities in information professions": "A",
        "Write and present for professional contexts (e.g., client reports, presentations)": "L",
        "Write Short  Essays ": "C",
        "Be able to develop a plan to address complex or ambiguous problems": "C",
        "Presentation/demonstration (prepared)": "C",
        "Project management": "L",
        "Project scheduling, tracking": "L",
        "Team work / effective group collaboration": "C",
        "Team dynamics and conflict resolution": "C",
        "Problem Solving Strategies": "L",
        "Motivation & Human Needs": "A",
        "Competititve analysis": "A",
        "Ideation / brainstorming": "A",
        "Thriving in ambiguous environments": "C",
        "Successfully powering through failure": "C",
        "Willingness to embrace calculated risks": "C",
        "Embracing life outside of the comfort zone": "C"
      }
    },
    "Ethics and Information Technology": {
      "courseID": "SI 410",
      "Pre-reqs": {
        "Ethics Of Info Use and Behavior ": "C",
        "Write for research-oriented audiences": "L",
        "Write Short  Essays ": "C"
      },
      "Outcomes": {
        "Build and maintain relationships through social media": "C",
        "Manage social media monitoring capabilities": "C",
        "Ethics Of Info Use and Behavior ": "C",
        "Reflect Critically On Own Use Of Info System": "C",
        "Write engaging social media content": "C"
      }
    },
  }];

